### PR TITLE
Get correct bounding coordinates for the canvas element

### LINKED ISSUE #29: Does not work with position relative on the parent element
The following breaks the example:

Modify index.html by adding `position: relative` to the pattern-container class:

    .pattern-container {
			text-align: center;
			max-width: 600px;
			margin: 0 auto;
			padding: 1em;
                    position: relative;
    }
    
This will break the demo.  I figured this was because of invalid bounding coordinates for the canvas element when using relative positioning: https://github.com/phenax/pattern-lock-js/pull/28

### PR DESCRIPTION
**Pull request by jitinl**
Fixes #29

### CODE REVIEW

File: src/PatternLock.js [hunk 1]
```diff
@@ -207,8 +207,8 @@ export class PatternLock {
 
 	// recalculateBounds :: () -> Point
 	recalculateBounds = () => this.bounds = ({
-		x: this.$canvas.offsetLeft,
-		y: this.$canvas.offsetTop,
+		x: this.$canvas.getBoundingClientRect().left,
```
Comment (phenax) [inline src/PatternLock.js:210]: Could you save `this.$canvas.getBoundingClientRect()` in a variable?
